// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info describes the currently open database.
 */
export interface Info {
    "path": string;
    "name": string;
    "readOnly": boolean;
}
