// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Column {
    "name": string;
    "type": string;
    "notNull": boolean;
    "default": string | null;
    "pk": number;
    "generated": boolean;
}

export interface ForeignKey {
    "table": string;
    "from": string[] | null;
    "to": string[] | null;
    "onUpdate": string;
    "onDelete": string;
}

export interface IncomingFK {
    "table": string;
    "from": string[] | null;
    "to": string[] | null;
}

export interface TableInfo {
    "name": string;
    "kind": string;
}

export interface TableSchema {
    "name": string;
    "kind": string;
    "readOnly": boolean;
    "columns": Column[] | null;
    "primaryKey": string[] | null;
    "usesRowId": boolean;
    "keyColumns": string[] | null;
    "foreignKeys": ForeignKey[] | null;
    "incoming": IncomingFK[] | null;
}
