// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Cond {
    "column": string;
    "value": any;
}

export interface Page {
    "rows": Row[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

export interface Query {
    "table": string;
    "page": number;
    "pageSize": number;
    "orderBy": string;
    "desc": boolean;
    "filter": string;
    "where": Cond[] | null;
}

export interface RefCount {
    "table": string;
    "from": string[] | null;
    "to": string[] | null;
    "count": number;
}

export interface Row {
    "key": { [_ in string]?: any } | null;
    "values": { [_ in string]?: any } | null;
}
